version: '3.8'

services:
  ldash:
    image: albertomoltrasio/ldash:latest
    container_name: ldash
    ports:
      - "6780:6780" # <- Port forward
    volumes:
      - ./data:/app/data  # <- DB bind mount
    restart: unless-stopped