version: '3.8'

services:
  ldash:
    image: albertomoltrasio/ldash:latest
    container_name: ldash
    ports:
      - "6780:6780"
    volumes:
      - ./data:/app/data  # <- DB bind mount
    environment:
      - PORT=6780
    restart: unless-stopped